---
title: 'Stat107 Final Project Data Cleaning'
author: "Group 15"()
date: "11-5-25"
output:
  pdf_document: default
  html_document:
    css: ../lab.css
    highlight: pygments
    theme: cerulean
---

```{r load-data}
sleep_data <- read.csv("human_cognitive_performance.csv")
head(sleep_data)
dim(sleep_data)
```

In order to ensure the data is ready for use in our analysis, we must first clean it such that each variable is formatted in a predicatble manner and there are not missing data values. To do this we define the below functions:

```{r}
#######################################################
##These functions are taken from DA6
#######################################################
remove_na <- function(df) { ## Automatize the removal of missing observations.
  n_obs <- nrow(df)
  missing <- rep(FALSE, n_obs)
  for (obs_ind in 1:n_obs) {
    obs <- df[obs_ind, ]
    n_missing <- sum(is.na(obs))
    if(n_missing > 0) {
      missing[obs_ind] <- TRUE
    }
  }
  df_red <- df[!missing, ]

  return(df_red)
}

#######################################################
#######################################################
to_factors <- function(df) { ## Turn all character variables to factors.
  n_vars <- ncol(df)
  for (var_ind in 1:n_vars) {
    var <- df[, var_ind]
    if (class(var) == "character") {
      df[, var_ind] <- factor(var)
    }
  }
  return(df)
}

```

Apply the functions to the data set:

```{r}
sleep_df <- to_factors(remove_na(sleep_data))
head(sleep_df)
```
```{r}
sleep_df <- sleep_df[c("Age", "Gender", "Sleep_Duration", "Stress_Level", "Diet_Type", "Daily_Screen_Time", "Exercise_Frequency", "Caffeine_Intake", "Reaction_Time", "Cognitive_Score")]
head(sleep_df)
dim(sleep_df)
sleep_df <- sleep_df[sleep_df$Age <= 25 && sleep_df$Age >= 18]
```

Remove outliers? 


Export the now cleaned data:

```{r}
save(sleep_df, file = "sleep_df.RData")
```


